//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticDotNet.ArgumentValidation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticDotNet.ArgumentValidation.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See inner excepetion for details..
        /// </summary>
        internal static string SEE_INNER_EXCEPTION_FOR_DETAILS {
            get {
                return ResourceManager.GetString("SEE_INNER_EXCEPTION_FOR_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        internal static string VALUE_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be white space..
        /// </summary>
        internal static string VALUE_CANNOT_BE_WHITE_SPACE {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_BE_WHITE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot have a length greater than {0}..
        /// </summary>
        internal static string VALUE_CANNOT_HAVE_LENGTH_GREATER_THAN {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_HAVE_LENGTH_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot have a length less than {0}..
        /// </summary>
        internal static string VALUE_CANNOT_HAVE_LENGTH_LESS_THAN {
            get {
                return ResourceManager.GetString("VALUE_CANNOT_HAVE_LENGTH_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must be an absolute uri..
        /// </summary>
        internal static string VALUE_MUST_BE_ABSOLUTE_URI {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_ABSOLUTE_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must be an absolute uri with scheme {1}..
        /// </summary>
        internal static string VALUE_MUST_BE_ABSOLUTE_WITH_SCHEME {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_ABSOLUTE_WITH_SCHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be assignable to {0}..
        /// </summary>
        internal static string VALUE_MUST_BE_ASSIGNABLE_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_ASSIGNABLE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1}..
        /// </summary>
        internal static string VALUE_MUST_BE_BETWEEN {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a digit..
        /// </summary>
        internal static string VALUE_MUST_BE_DIGIT {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be equal to {0}..
        /// </summary>
        internal static string VALUE_MUST_BE_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be false..
        /// </summary>
        internal static string VALUE_MUST_BE_FALSE {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than {0}..
        /// </summary>
        internal static string VALUE_MUST_BE_GREATER_THAN {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to {0}..
        /// </summary>
        internal static string VALUE_MUST_BE_GREATER_THAN_OR_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_GREATER_THAN_OR_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than {0}..
        /// </summary>
        internal static string VALUE_MUST_BE_LESS_THAN {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than or equal to {0}..
        /// </summary>
        internal static string VALUE_MUST_BE_LESS_THAN_OR_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_LESS_THAN_OR_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a letter..
        /// </summary>
        internal static string VALUE_MUST_BE_LETTER {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a letter or digit..
        /// </summary>
        internal static string VALUE_MUST_BE_LETTER_OR_DIGIT {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_LETTER_OR_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be lower..
        /// </summary>
        internal static string VALUE_MUST_BE_LOWER {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be null..
        /// </summary>
        internal static string VALUE_MUST_BE_NULL {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number..
        /// </summary>
        internal static string VALUE_MUST_BE_NUMBER {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be parsable to {0}..
        /// </summary>
        internal static string VALUE_MUST_BE_PARSABLE_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_PARSABLE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be readable..
        /// </summary>
        internal static string VALUE_MUST_BE_READABLE {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_READABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must be a relative uri..
        /// </summary>
        internal static string VALUE_MUST_BE_RELATIVE {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_RELATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be the same..
        /// </summary>
        internal static string VALUE_MUST_BE_SAME {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be seekable..
        /// </summary>
        internal static string VALUE_MUST_BE_SEEKABLE {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_SEEKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be true..
        /// </summary>
        internal static string VALUE_MUST_BE_TRUE {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be upper..
        /// </summary>
        internal static string VALUE_MUST_BE_UPPER {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be writable..
        /// </summary>
        internal static string VALUE_MUST_BE_WRITABLE {
            get {
                return ResourceManager.GetString("VALUE_MUST_BE_WRITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must contain {0}..
        /// </summary>
        internal static string VALUE_MUST_CONTAIN {
            get {
                return ResourceManager.GetString("VALUE_MUST_CONTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must end with {0}..
        /// </summary>
        internal static string VALUE_MUST_END_WITH {
            get {
                return ResourceManager.GetString("VALUE_MUST_END_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have DateTimeKind.Local..
        /// </summary>
        internal static string VALUE_MUST_HAVE_DATETIMEKIND_LOCAL {
            get {
                return ResourceManager.GetString("VALUE_MUST_HAVE_DATETIMEKIND_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have DateTimeKind.Utc..
        /// </summary>
        internal static string VALUE_MUST_HAVE_DATETIMEKIND_UTC {
            get {
                return ResourceManager.GetString("VALUE_MUST_HAVE_DATETIMEKIND_UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have a length between {0} and {1}..
        /// </summary>
        internal static string VALUE_MUST_HAVE_LENGTH_BETWEEN {
            get {
                return ResourceManager.GetString("VALUE_MUST_HAVE_LENGTH_BETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have a length equal to {0}..
        /// </summary>
        internal static string VALUE_MUST_HAVE_LENGTH_EQUAL_TO {
            get {
                return ResourceManager.GetString("VALUE_MUST_HAVE_LENGTH_EQUAL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must match the regex {0}..
        /// </summary>
        internal static string VALUE_MUST_MATCH_REGEX {
            get {
                return ResourceManager.GetString("VALUE_MUST_MATCH_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must start with {0}..
        /// </summary>
        internal static string VALUE_MUST_START_WITH {
            get {
                return ResourceManager.GetString("VALUE_MUST_START_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not defined..
        /// </summary>
        internal static string VALUE_NOT_DEFINED {
            get {
                return ResourceManager.GetString("VALUE_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is unexpectedly null. Please use Arg.IsNotNull..
        /// </summary>
        internal static string VALUE_UNEXPECTED_NULL {
            get {
                return ResourceManager.GetString("VALUE_UNEXPECTED_NULL", resourceCulture);
            }
        }
    }
}
