name: Pull Request

run-name: Pull Request from ${{ github.ref_name }} into ${{ github.base_ref }}

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest
    steps:

      - name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v5
  
      - name: Setup DotNet
        uses: actions/setup-dotnet@v5

      - name: Restore Packages
        run: dotnet restore ./src

      - name: Build
        run: dotnet build ./src --no-restore

      - name: Test
        run: dotnet test ./src --no-restore --no-build